### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by SouthEndMusic** [SouthEndMusic/Rays#72]
Generate a docs website as also done for `Ribasim`.

Should contain (roughly per page):
- [ ] General introduction
- [ ] Descriptions of shapes and associated intersection algorithms
- [ ] `Getting_started.ipynb` (cell outputs created when rendering docs) 
- [ ] `Interactive_rendering.ipynb` (without cell outputs)
- [ ] Description of how to set up interactive rendering with reference to `Interactive_rendering.ipynb`
